version: "3"

services:
  app:
    container_name: calendar-app
    build:
      context: ./..
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres


  postgres:
    container_name: calendar-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calendar
    volumes:
    - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54320:5432"