[logger]
level = "INFO"

[app]
host = "0.0.0.0"
port = "3000"

[database]
enabled = true
connection = "postgres"
host = "localhost"
port = "5432"
user = "root"
passowrd = "password"
database = "calendar"